name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        env:
          CGO_ENABLED: '0'
        run: GOOS=linux GOARCH=amd64 go build ./...

      - name: Unit tests
        run: go test ./api/...
